{
	"version": 1615981088,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/bubble-sheet0.png",
		"images/spawner-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bg3-sheet0.png",
		"images/bubbledel-sheet0.png",
		"images/bubbledel-sheet1.png",
		"media/create.m4a",
		"media/create.ogg",
		"media/explode.m4a",
		"media/explode.ogg",
		"media/diamond mqt - b.i.g big hit ft. og-anic (prod. by 3lackondabeat) (online-audio-converter.com).m4a",
		"media/diamond mqt - b.i.g big hit ft. og-anic (prod. by 3lackondabeat) (online-audio-converter.com).ogg",
		"media/nanatsu no taizai ost - eri0ne [hd] (online-audio-converter.com).m4a",
		"media/nanatsu no taizai ost - eri0ne [hd] (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}